#!/usr/bin/env python3
"""Standalone memory sync helper for Codex and Claude Code repos."""
from __future__ import annotations

import argparse
from pathlib import Path


GENERATED_BANNER = "<!-- Generated by memory-sync. Edit memory/project.md instead. -->\n"

PROJECT_TEMPLATE = """# Project Memory

## Working Style

- Keep changes direct and pragmatic.
- Verify important changes with concrete checks.

## User Preferences

- Add durable corrections here when they should persist across sessions.
"""

CLAUDE_OVERLAY_TEMPLATE = """## Claude Code

- Add Claude-specific notes here only when they are truly host-specific.
"""


def canonical_memory(repo: Path) -> Path:
    return repo / "memory" / "project.md"


def claude_overlay(repo: Path) -> Path:
    return repo / "memory" / "claude.md"


def agents_output(repo: Path) -> Path:
    return repo / "AGENTS.md"


def claude_output(repo: Path) -> Path:
    return repo / "CLAUDE.md"


def render_agents(shared_memory: str) -> str:
    return GENERATED_BANNER + "\n" + shared_memory.strip() + "\n"


def render_claude(overlay: str | None = None) -> str:
    body = [GENERATED_BANNER.rstrip(), "", "@AGENTS.md"]
    if overlay and overlay.strip():
        body.extend(["", overlay.strip()])
    return "\n".join(body).rstrip() + "\n"


def init_repo(repo: Path, force: bool = False) -> None:
    repo = repo.resolve()
    repo.joinpath("memory").mkdir(parents=True, exist_ok=True)

    shared = canonical_memory(repo)
    if force or not shared.exists():
        shared.write_text(PROJECT_TEMPLATE.strip() + "\n", encoding="utf-8")

    overlay = claude_overlay(repo)
    if force or not overlay.exists():
        overlay.write_text(CLAUDE_OVERLAY_TEMPLATE.strip() + "\n", encoding="utf-8")

    sync_repo(repo)


def sync_repo(repo: Path) -> None:
    repo = repo.resolve()
    shared = canonical_memory(repo)
    if not shared.exists():
        raise FileNotFoundError(f"Missing canonical memory file: {shared}")

    shared_text = shared.read_text(encoding="utf-8")
    overlay_path = claude_overlay(repo)
    overlay_text = overlay_path.read_text(encoding="utf-8") if overlay_path.exists() else None

    agents_output(repo).write_text(render_agents(shared_text), encoding="utf-8")
    claude_output(repo).write_text(render_claude(overlay_text), encoding="utf-8")


def check_repo(repo: Path) -> list[str]:
    repo = repo.resolve()
    shared = canonical_memory(repo)
    if not shared.exists():
        raise FileNotFoundError(f"Missing canonical memory file: {shared}")

    shared_text = shared.read_text(encoding="utf-8")
    overlay_path = claude_overlay(repo)
    overlay_text = overlay_path.read_text(encoding="utf-8") if overlay_path.exists() else None

    expected = {
        "AGENTS.md": render_agents(shared_text),
        "CLAUDE.md": render_claude(overlay_text),
    }
    actual_paths = {
        "AGENTS.md": agents_output(repo),
        "CLAUDE.md": claude_output(repo),
    }

    mismatches: list[str] = []
    for name, expected_text in expected.items():
        path = actual_paths[name]
        actual_text = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual_text != expected_text:
            mismatches.append(name)
    return mismatches


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Sync shared memory for Codex and Claude Code.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Initialize canonical memory and generated files.")
    init_parser.add_argument("--repo", default=".", help="Target repository path")
    init_parser.add_argument("--force", action="store_true", help="Overwrite starter templates if present")

    sync_parser = subparsers.add_parser("sync", help="Regenerate AGENTS.md and CLAUDE.md.")
    sync_parser.add_argument("--repo", default=".", help="Target repository path")

    check_parser = subparsers.add_parser("check", help="Fail if generated files are stale.")
    check_parser.add_argument("--repo", default=".", help="Target repository path")

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    repo = Path(args.repo).resolve()

    if args.command == "init":
        init_repo(repo, force=args.force)
        print(f"Initialized memory sync in {repo}")
        return 0

    if args.command == "sync":
        sync_repo(repo)
        print(f"Synchronized memory files in {repo}")
        return 0

    if args.command == "check":
        mismatches = check_repo(repo)
        if mismatches:
            print("Out of sync: " + ", ".join(mismatches))
            return 1
        print("Memory files are in sync.")
        return 0

    parser.error(f"Unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
